apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-api
  labels:
    app: expense-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: expense-api
  template:
    metadata:
      labels:
        app: expense-api
    spec:
      containers:
        - name: expense-api
          image: YOUR_DOCKERHUB_USERNAME/expense-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
